[phases.setup]
commands = [
  "pip install -r requirements.txt",
  "cd client && npm install"
]

[phases.start]
commands = [
  "cd client && npm start &",
  "python manage.py runserver 0.0.0.0:8000"
]
